# Generated by Django 4.0.5 on 2022-12-05 15:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='favroute',
            name='altitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='favroute',
            name='surface',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[], size=None),
        ),
        migrations.AddField(
            model_name='favroute',
            name='xaxis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
    ]
